spring.application.name=MasterRepo

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/master-repo}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/master-repo/protocol/openid-connect/certs

# Spring Security Logging pour le debug
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
